/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class snakepackage_Snake */

#ifndef _Included_snakepackage_Snake
#define _Included_snakepackage_Snake
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     snakepackage_Snake
 * Method:    controls
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_snakepackage_Snake_controls
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
